[package]
name = "fonttype"
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"
description = "A font parsing and manipulation library"
homepage = "https://github.com/yingkitw/fonttype"
repository = "https://github.com/yingkitw/fonttype"
documentation = "https://docs.rs/fonttype"
keywords = ["font", "type", "parser", "manipulator"]
categories = ["graphics", "multimedia::images"]

[dependencies]
byteorder = "1.5"
thiserror = "1.0"
clap = { version = "4.5", features = ["derive"] }
flate2 = "1.0"
brotli = "7"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }

[[bin]]
name = "fonttype"
path = "src/main.rs"

[lib]
name = "fonttype"
path = "src/lib.rs"

