pub mod error;
pub mod parse;
pub mod write;
pub mod font;
pub mod tables;
pub mod image;
pub mod woff;
pub mod woff2;
pub mod ttc;
pub mod bezier;
pub mod encoding;
pub mod modifier;
pub mod validation;

pub use font::Font;
pub use error::{FontError, Tag};
pub use tables::Table;
pub use woff::{read_woff, write_woff};
pub use woff2::{read_woff2, write_woff2};
pub use ttc::Ttc;
pub use bezier::BezierEditor;
pub use encoding::{CharMapping, EncodingManager, EncodingTable, EncodingType};
pub use modifier::FontModifier;
pub use validation::{IssueCategory, IssueSeverity, ValidationIssue, ValidationReport};
